from django.urls import path
from . import views

urlpatterns = [
    path("", views.dashboard, name="dashboard"),
    path("firmalar/", views.firmalar, name="firmalar"),
    path("obyekt/<int:pk>/", views.project_detail, name="project_detail"),
    path("obyekt/<int:pk>/limit/", views.limit_edit, name="limit_edit"),
    path("obyekt/<int:pk>/limit-ichi/", views.limit_items_edit, name="limit_items_edit"),
    path("obyekt/<int:pk>/limit/qaytarish/", views.limit_return_pto, name="limit_return_pto"),
    path("haftalik/<int:pk>/qaytarish/", views.weekly_return_pto, name="weekly_return_pto"),
    path("haftalik/<int:pk>/export/", views.weekly_export, name="weekly_export"),
    path("xabarlar/", views.xabar_yuborish, name="xabar_yuborish"),
    path("xabarlar/<int:pk>/oqidim/", views.xabar_oqidim, name="xabar_oqidim"),
    path("limit/bulk/", views.limit_bulk, name="limit_bulk"),
    path("tasdiqlar/", views.tasdiqlar, name="tasdiqlar"),
    path("virtual-ofis/", views.virtual_ofis, name="virtual_ofis"),
    path("m29/", views.m29, name="m29"),
    path("haftalik-tarix/", views.haftalik_tarix, name="haftalik_tarix"),
    path("limit-sorov/<int:pk>/amal/", views.limit_request_action, name="limit_request_action"),
    path("limit-sorov/<int:pk>/tahrir/", views.limit_request_edit, name="limit_request_edit"),
    path("obyekt/<int:pk>/haftalik/qoshish/", views.weekly_add, name="weekly_add"),
    path("haftalik/<int:pk>/amal/", views.weekly_action, name="weekly_action"),
    path("haftalik/<int:pk>/tahrir/", views.weekly_edit, name="weekly_edit"),
    path("limit/export/", views.limit_export, name="limit_export"),
    path("hisobotlar/zip/", views.hisobotlar_zip, name="hisobotlar_zip"),
    path("obyekt/<int:pk>/limit/export/", views.limit_export_obj, name="limit_export_obj"),
    path("limit/template/", views.limit_template, name="limit_template"),
    path("limit/grafik-qolip/", views.grafik_template, name="grafik_template"),
    path("grafik-ish-qolip/", views.grafik_rabota, name="grafik_rabota"),
    path("obyekt/<int:pk>/grafik-ish/", views.grafik_rabota, name="grafik_rabota_obj"),
    path("grafik/", views.grafik_list, name="grafik_list"),
    path("obyekt/<int:pk>/grafik/", views.grafik_web, name="grafik_web"),
    path("obyekt/<int:pk>/grafik/tasdiqqa/", views.grafik_tasdiq_yubor, name="grafik_tasdiq_yubor"),
    path("grafik-tasdiq/<int:pk>/amal/", views.grafik_tasdiq_action, name="grafik_tasdiq_action"),
    path("limit/import/", views.limit_import, name="limit_import"),
    # Prorab -> PTO material so'rovi
    path("material-sorov/", views.material_sorov, name="material_sorov"),
    path("material-sorov/yangi/", views.material_sorov_add, name="material_sorov_add"),
    path("material-sorov/<int:pk>/", views.material_sorov_korish, name="material_sorov_korish"),
    path("material-sorov/<int:pk>/amal/", views.material_sorov_action, name="material_sorov_action"),
]
