# Generated by Django 6.0.6 on 2026-06-25 07:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=64, unique=True, verbose_name='Kod')),
                ('name', models.CharField(max_length=255, verbose_name='Nomi')),
                ('status', models.CharField(choices=[('active', 'Faol'), ('paused', "To'xtatilgan"), ('done', 'Yakunlangan')], default='active', max_length=16, verbose_name='Holati')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan')),
            ],
            options={
                'verbose_name': 'Obyekt',
                'verbose_name_plural': 'Obyektlar',
            },
        ),
        migrations.CreateModel(
            name='WorkSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=64, verbose_name='Kod')),
                ('name', models.CharField(max_length=255, verbose_name='Nomi')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='projects.worksection', verbose_name="Yuqori bo'lim")),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_sections', to='projects.project', verbose_name='Obyekt')),
            ],
            options={
                'verbose_name': "Ish bo'limi",
                'verbose_name_plural': "Ish bo'limlari",
            },
        ),
    ]
