# Generated by Django 6.0.6 on 2026-06-29 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='budget_total',
            field=models.DecimalField(decimal_places=2, default=0, help_text="0 = limit yo'q. Oshsa: RUXSAT KERAK.", max_digits=18, verbose_name='Umumiy limit'),
        ),
        migrations.AddField(
            model_name='project',
            name='budget_weekly',
            field=models.DecimalField(decimal_places=2, default=0, help_text="0 = limit yo'q. Faqat ko'rsatkich.", max_digits=18, verbose_name='Haftalik limit'),
        ),
    ]
