# Generated by Django 6.0.6 on 2026-07-04 07:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_budget_total_project_budget_weekly'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklyRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start', models.DateField(verbose_name='Hafta boshi')),
                ('week_end', models.DateField(verbose_name='Hafta oxiri')),
                ('number', models.CharField(blank=True, max_length=64, verbose_name='Hujjat raqami')),
                ('status', models.CharField(choices=[('draft', 'Qoralama'), ('approved', 'Tasdiqlangan')], default='draft', help_text="Faqat «Tasdiqlangan» so'rovlar limitdan ayiriladi.", max_length=16, verbose_name='Holati')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='Izoh')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_requests', to='projects.project', verbose_name='Obyekt')),
            ],
            options={
                'verbose_name': "Haftalik so'rov",
                'verbose_name_plural': "Haftalik so'rovlar",
                'ordering': ['-week_start', '-id'],
            },
        ),
        migrations.CreateModel(
            name='WeeklyRequestItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('material', 'Material'), ('labor', 'Ish haqi')], default='material', max_length=16, verbose_name='Turi')),
                ('name', models.CharField(max_length=255, verbose_name='Material / ish nomi')),
                ('unit', models.CharField(blank=True, max_length=32, verbose_name="O'lchov birligi")),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=18, verbose_name='Objём')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='Narxi (1 birlik)')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='projects.weeklyrequest', verbose_name="So'rov")),
                ('work_section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='weekly_items', to='projects.worksection', verbose_name="Ish bo'limi")),
            ],
            options={
                'verbose_name': "So'rov qatori",
                'verbose_name_plural': "So'rov qatorlari",
            },
        ),
    ]
