# Generated by Django 6.0.6 on 2026-07-04 09:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_weeklyrequest_weeklyrequestitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstimateLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block', models.CharField(blank=True, max_length=64, verbose_name='Blok')),
                ('kind', models.CharField(choices=[('material', 'Material'), ('labor', 'Ish haqi')], default='material', max_length=16, verbose_name='Turi')),
                ('name', models.CharField(max_length=255, verbose_name='Material / ish nomi')),
                ('unit', models.CharField(blank=True, max_length=32, verbose_name="O'lchov birligi")),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=18, verbose_name='Objём')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='Narxi (1 birlik)')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estimate_lines', to='projects.project', verbose_name='Obyekt')),
                ('work_section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estimate_lines', to='projects.worksection', verbose_name="Ish bo'limi")),
            ],
            options={
                'verbose_name': 'Smeta qatori',
                'verbose_name_plural': "Smeta (ma'lumotnoma)",
                'ordering': ['work_section__name', 'block', 'kind', 'name'],
            },
        ),
    ]
