# Generated by Django 6.0.6 on 2026-07-04 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_estimateline'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EstimateLine',
        ),
    ]
