# Generated by Django 6.0.6 on 2026-07-04 11:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_delete_estimateline'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LimitChangeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_value', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='Eski limit')),
                ('new_value', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='Yangi limit')),
                ('reason', models.CharField(blank=True, max_length=255, verbose_name='Sabab / izoh')),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('approved', 'Tasdiqlangan'), ('rejected', 'Rad etilgan')], default='pending', max_length=16, verbose_name='Holati')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan')),
                ('decided_at', models.DateTimeField(blank=True, null=True, verbose_name='Qaror sanasi')),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='limit_requests_decided', to=settings.AUTH_USER_MODEL, verbose_name='Qaror qilgan (admin)')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='limit_requests', to='projects.project', verbose_name='Obyekt')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='limit_requests_made', to=settings.AUTH_USER_MODEL, verbose_name="So'rovchi (PTO)")),
            ],
            options={
                'verbose_name': "Limit o'zgartirish so'rovi",
                'verbose_name_plural': "Limit o'zgartirish so'rovlari",
                'ordering': ['-created_at'],
            },
        ),
    ]
