# Generated by Django 6.0.6 on 2026-07-04 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_limitchangerequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='limitchangerequest',
            name='new_value',
        ),
        migrations.RemoveField(
            model_name='limitchangerequest',
            name='old_value',
        ),
        migrations.RemoveField(
            model_name='project',
            name='budget_weekly',
        ),
        migrations.AddField(
            model_name='limitchangerequest',
            name='new_labor',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='Yangi ish haqi'),
        ),
        migrations.AddField(
            model_name='limitchangerequest',
            name='new_machinery',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='Yangi mashina chasti'),
        ),
        migrations.AddField(
            model_name='limitchangerequest',
            name='new_material',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='Yangi material'),
        ),
        migrations.AddField(
            model_name='limitchangerequest',
            name='old_labor',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='Eski ish haqi'),
        ),
        migrations.AddField(
            model_name='limitchangerequest',
            name='old_machinery',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='Eski mashina chasti'),
        ),
        migrations.AddField(
            model_name='limitchangerequest',
            name='old_material',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='Eski material'),
        ),
        migrations.AddField(
            model_name='project',
            name='limit_labor',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='Ish haqi limiti'),
        ),
        migrations.AddField(
            model_name='project',
            name='limit_machinery',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='Mashina chasti limiti'),
        ),
        migrations.AddField(
            model_name='project',
            name='limit_material',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='Material limiti'),
        ),
        migrations.AlterField(
            model_name='project',
            name='budget_total',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=18, verbose_name='Umumiy limit (eski)'),
        ),
        migrations.AlterField(
            model_name='weeklyrequestitem',
            name='kind',
            field=models.CharField(choices=[('material', 'Material'), ('labor', 'Ish haqi'), ('machinery', 'Mashina chasti')], default='material', max_length=16, verbose_name='Turi'),
        ),
    ]
