# Generated by Django 6.0.6 on 2026-07-04 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_remove_limitchangerequest_new_value_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='budget_total',
        ),
    ]
