# Generated by Django 6.0.6 on 2026-07-06 03:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_remove_project_budget_total'),
    ]

    operations = [
        migrations.CreateModel(
            name='Firma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Nomi')),
                ('inn', models.CharField(blank=True, max_length=20, verbose_name='STIR')),
                ('director', models.CharField(blank=True, max_length=255, verbose_name='Rahbar')),
                ('phone', models.CharField(blank=True, max_length=64, verbose_name='Telefon')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Manzil')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='Izoh')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan')),
            ],
            options={
                'verbose_name': 'Firma',
                'verbose_name_plural': 'Firmalar',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='project',
            name='firma',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='projects.firma', verbose_name='Firma'),
        ),
    ]
