# Generated by Django 6.0.6 on 2026-07-06 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_firma_project_firma'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Tugash sanasi'),
        ),
        migrations.AddField(
            model_name='project',
            name='location',
            field=models.CharField(blank=True, max_length=255, verbose_name='Manzil / joy'),
        ),
        migrations.AddField(
            model_name='project',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Boshlanish sanasi'),
        ),
    ]
