# Generated by Django 6.0.6 on 2026-07-09 09:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_project_end_date_project_location_project_start_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='LimitChangeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('material', 'Material'), ('labor', 'Ish haqi'), ('machinery', 'Mashina chasti')], default='material', max_length=16, verbose_name='Turi')),
                ('name', models.CharField(max_length=255, verbose_name='Nomi')),
                ('unit', models.CharField(blank=True, max_length=32, verbose_name="O'lchov birligi")),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=18, verbose_name='Miqdor')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='Narxi (1 birlik)')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposed_items', to='projects.limitchangerequest', verbose_name="So'rov")),
            ],
            options={
                'verbose_name': 'Taklif tarkibi',
                'verbose_name_plural': 'Taklif tarkibi',
            },
        ),
        migrations.CreateModel(
            name='LimitItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('material', 'Material'), ('labor', 'Ish haqi'), ('machinery', 'Mashina chasti')], default='material', max_length=16, verbose_name='Turi')),
                ('name', models.CharField(max_length=255, verbose_name='Nomi')),
                ('unit', models.CharField(blank=True, max_length=32, verbose_name="O'lchov birligi")),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=18, verbose_name='Miqdor')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='Narxi (1 birlik)')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='limit_items', to='projects.project', verbose_name='Obyekt')),
            ],
            options={
                'verbose_name': 'Limit tarkibi',
                'verbose_name_plural': 'Limit tarkibi (ichi)',
            },
        ),
    ]
