# Generated by Django 6.0.6 on 2026-07-20 04:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_limitchangeitem_limititem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='weeklyrequest',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Tasdiqlangan sana'),
        ),
        migrations.AddField(
            model_name='weeklyrequest',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='weekly_approved', to=settings.AUTH_USER_MODEL, verbose_name='Tasdiqladi (admin)'),
        ),
        migrations.AddField(
            model_name='weeklyrequest',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='weekly_created', to=settings.AUTH_USER_MODEL, verbose_name='Kiritdi (PTO)'),
        ),
        migrations.AlterField(
            model_name='weeklyrequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Kiritilgan sana'),
        ),
    ]
