# Generated by Django 6.0.6 on 2026-07-20 12:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_weeklyrequest_approved_at_weeklyrequest_approved_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='grafik_start',
            field=models.DateField(blank=True, null=True, verbose_name='Grafik boshlanish sanasi'),
        ),
        migrations.CreateModel(
            name='GrafikRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tartib', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
                ('name', models.CharField(blank=True, max_length=500, verbose_name='Наименование (ish nomi)')),
                ('unit', models.CharField(blank=True, max_length=32, verbose_name='Ед.изм')),
                ('qty', models.DecimalField(decimal_places=3, default=0, max_digits=18, verbose_name='Кол-во')),
                ('plan', models.DecimalField(decimal_places=3, default=0, max_digits=18, verbose_name='Кун план')),
                ('responsible', models.CharField(blank=True, max_length=255, verbose_name='Маъсул шахс')),
                ('note', models.CharField(blank=True, max_length=500, verbose_name='Иш прагнози / izoh')),
                ('days', models.JSONField(blank=True, default=dict, verbose_name='Kunlik bajarilgan')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grafik_rows', to='projects.project', verbose_name='Obyekt')),
            ],
            options={
                'verbose_name': 'Grafik qatori',
                'verbose_name_plural': 'Grafik qatorlari',
                'ordering': ['tartib', 'id'],
            },
        ),
    ]
