# Generated by Django 6.0.6 on 2026-07-22 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0013_project_grafik_start_grafikrow'),
    ]

    operations = [
        migrations.AddField(
            model_name='weeklyrequestitem',
            name='note',
            field=models.CharField(blank=True, max_length=500, verbose_name='Primechaniye (qator izohi)'),
        ),
    ]
