# Generated by Django 6.0.6 on 2026-07-22 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0014_weeklyrequestitem_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='limitchangerequest',
            name='decision_note',
            field=models.CharField(blank=True, max_length=500, verbose_name='Admin izohi / rad etish sababi'),
        ),
    ]
