# Generated by Django 6.0.6 on 2026-07-22 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0015_limitchangerequest_decision_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='limitchangeitem',
            name='note',
            field=models.CharField(blank=True, max_length=500, verbose_name='Primechaniye (qator izohi)'),
        ),
        migrations.AddField(
            model_name='limititem',
            name='note',
            field=models.CharField(blank=True, max_length=500, verbose_name='Primechaniye (qator izohi)'),
        ),
    ]
