# Generated by Django 6.0.6 on 2026-07-22 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0016_limitchangeitem_note_limititem_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='limititem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name="Qo'shilgan sana"),
        ),
        migrations.AddField(
            model_name='limititem',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name="O'zgartirilgan sana"),
        ),
    ]
