# Generated by Django 6.0.6 on 2026-07-23 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0017_limititem_created_at_limititem_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weeklyrequestitem',
            name='quantity',
            field=models.DecimalField(decimal_places=3, max_digits=18, verbose_name='Miqdor'),
        ),
    ]
