# Generated by Django 6.0.6 on 2026-07-23 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0018_alter_weeklyrequestitem_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weeklyrequest',
            name='status',
            field=models.CharField(choices=[('draft', 'Qoralama'), ('submitted', 'Adminga yuborilgan'), ('approved', 'Tasdiqlangan')], default='draft', help_text="Faqat «Tasdiqlangan» so'rovlar limitdan ayiriladi.", max_length=16, verbose_name='Holati'),
        ),
    ]
