# Generated by Django 6.0.6 on 2026-07-23 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0019_alter_weeklyrequest_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='limitchangerequest',
            name='pto_notified',
            field=models.BooleanField(default=True, verbose_name="PTO xabarni ko'rdi"),
        ),
        migrations.AddField(
            model_name='weeklyrequest',
            name='pto_notified',
            field=models.BooleanField(default=True, verbose_name="PTO xabarni ko'rdi"),
        ),
    ]
