# Generated by Django 6.0.6 on 2026-07-23 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0020_limitchangerequest_pto_notified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='limitchangeitem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Kiritilgan sana'),
        ),
    ]
