# Generated by Django 6.0.6 on 2026-07-23 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0021_limitchangeitem_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='weeklyrequestitem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Kiritilgan sana'),
        ),
    ]
