# Generated by Django 6.0.6 on 2026-07-25 05:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0022_weeklyrequestitem_created_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='limitchangerequest',
            name='director_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name="Direktor tasdig'i sanasi"),
        ),
        migrations.AddField(
            model_name='limitchangerequest',
            name='director_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='limit_requests_dir', to=settings.AUTH_USER_MODEL, verbose_name='Direktor tasdiqladi'),
        ),
        migrations.AddField(
            model_name='weeklyrequest',
            name='director_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name="Direktor tasdig'i sanasi"),
        ),
        migrations.AddField(
            model_name='weeklyrequest',
            name='director_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='weekly_director', to=settings.AUTH_USER_MODEL, verbose_name='Direktor tasdiqladi'),
        ),
        migrations.AddField(
            model_name='weeklyrequest',
            name='reject_note',
            field=models.CharField(blank=True, max_length=500, verbose_name='Rad etish sababi'),
        ),
        migrations.AlterField(
            model_name='limitchangerequest',
            name='decision_note',
            field=models.CharField(blank=True, max_length=500, verbose_name='Rad etish sababi'),
        ),
        migrations.AlterField(
            model_name='limitchangerequest',
            name='status',
            field=models.CharField(choices=[('dir', "Direktor tasdig'ida"), ('adm', "Admin tasdig'ida"), ('pending', 'Kutilmoqda'), ('approved', 'Tasdiqlangan'), ('rejected', 'Rad etilgan')], default='dir', max_length=16, verbose_name='Holati'),
        ),
        migrations.AlterField(
            model_name='weeklyrequest',
            name='status',
            field=models.CharField(choices=[('draft', 'Qoralama'), ('dir', "Direktor tasdig'ida"), ('submitted', "Admin tasdig'ida"), ('approved', 'Tasdiqlangan')], default='draft', help_text="Faqat «Tasdiqlangan» so'rovlar limitdan ayiriladi.", max_length=16, verbose_name='Holati'),
        ),
    ]
