# Generated by Django 6.0.6 on 2026-07-30 04:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0025_userprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'Foydalanuvchi biriktirish', 'verbose_name_plural': 'Foydalanuvchi biriktirish'},
        ),
        migrations.AddField(
            model_name='userprofile',
            name='projects',
            field=models.ManyToManyField(blank=True, related_name='assigned_users', to='projects.project', verbose_name='Biriktirilgan obyektlar (PTO/Prorab uchun)'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='firma',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='projects.firma', verbose_name='Firma (direktor uchun)'),
        ),
        migrations.CreateModel(
            name='MaterialRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', "PTO ko'rib chiqishida"), ('accepted', 'Qabul qilingan'), ('rejected', 'Rad etilgan')], default='pending', max_length=16, verbose_name='Holati')),
                ('note', models.CharField(blank=True, max_length=500, verbose_name='Izoh')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yuborilgan sana')),
                ('decided_at', models.DateTimeField(blank=True, null=True, verbose_name='Qaror sanasi')),
                ('reject_note', models.CharField(blank=True, max_length=500, verbose_name='Rad etish sababi')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='material_requests_created', to=settings.AUTH_USER_MODEL, verbose_name='Prorab')),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='material_requests_decided', to=settings.AUTH_USER_MODEL, verbose_name='PTO')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_requests', to='projects.project', verbose_name='Obyekt')),
            ],
            options={
                'verbose_name': "Material so'rovi (Prorab)",
                'verbose_name_plural': "Material so'rovlari (Prorab)",
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MaterialRequestItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Material nomi')),
                ('unit', models.CharField(blank=True, max_length=32, verbose_name="O'lchov birligi")),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=18, verbose_name='Miqdor')),
                ('note', models.CharField(blank=True, max_length=500, verbose_name='Izoh')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='projects.materialrequest', verbose_name="So'rov")),
            ],
            options={
                'verbose_name': "So'rov qatori",
                'verbose_name_plural': "So'rov qatorlari",
            },
        ),
    ]
