# Generated by Django 6.0.6 on 2026-07-30 05:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0026_alter_userprofile_options_userprofile_projects_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.CharField(blank=True, choices=[('', "— (lavozim yo'q)"), ('director', 'Direktor'), ('pto', 'PTO'), ('prorab', 'Prorab')], max_length=16, verbose_name='Lavozim'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='firma',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='projects.firma', verbose_name='Firma (Direktor uchun)'),
        ),
    ]
