# Generated by Django 6.0.6 on 2026-08-01 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0027_userprofile_role_alter_userprofile_firma'),
    ]

    operations = [
        migrations.AddField(
            model_name='limitchangerequest',
            name='new_other',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name="Yangi ko'zda tutilmagan"),
        ),
        migrations.AddField(
            model_name='limitchangerequest',
            name='old_other',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name="Eski ko'zda tutilmagan"),
        ),
        migrations.AddField(
            model_name='project',
            name='limit_other',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name="Ko'zda tutilmagan xarajatlar limiti"),
        ),
        migrations.AlterField(
            model_name='limitchangeitem',
            name='kind',
            field=models.CharField(choices=[('material', 'Material'), ('labor', 'Ish haqi'), ('machinery', 'Mashina chasti'), ('other', "Ko'zda tutilmagan xarajatlar")], default='material', max_length=16, verbose_name='Turi'),
        ),
        migrations.AlterField(
            model_name='limititem',
            name='kind',
            field=models.CharField(choices=[('material', 'Material'), ('labor', 'Ish haqi'), ('machinery', 'Mashina chasti'), ('other', "Ko'zda tutilmagan xarajatlar")], default='material', max_length=16, verbose_name='Turi'),
        ),
        migrations.AlterField(
            model_name='weeklyrequestitem',
            name='kind',
            field=models.CharField(choices=[('material', 'Material'), ('labor', 'Ish haqi'), ('machinery', 'Mashina chasti'), ('other', "Ko'zda tutilmagan xarajatlar")], default='material', max_length=16, verbose_name='Turi'),
        ),
    ]
