# Generated by Django 6.0.7 on 2026-08-01 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0028_limitchangerequest_new_other_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramBindState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.CharField(max_length=32, unique=True, verbose_name='Chat ID')),
                ('step', models.CharField(blank=True, max_length=16, verbose_name='Bosqich')),
                ('login_tmp', models.CharField(blank=True, max_length=150, verbose_name='Vaqtinchalik login')),
                ('fails', models.PositiveSmallIntegerField(default=0, verbose_name='Xato urinishlar')),
                ('blocked_until', models.DateTimeField(blank=True, null=True, verbose_name='Bloklangan (gacha)')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': "Telegram bog'lash holati",
                'verbose_name_plural': "Telegram bog'lash holatlari",
            },
        ),
        migrations.AddField(
            model_name='userprofile',
            name='telegram_chat_id',
            field=models.CharField(blank=True, default='', help_text="Bo'sh bo'lsa — oddiy login/parol bilan kiradi. To'ldirilgan bo'lsa — kirishda shu chatga tasdiqlash kodi boradi. Foydalanuvchi botga /start yozib login/parol bilan o'zi bog'lanadi.", max_length=32, verbose_name='Telegram chat ID (2FA)'),
        ),
    ]
