# Generated by Django 6.0.7 on 2026-08-01 12:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0029_telegrambindstate_userprofile_telegram_chat_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='telegrambindstate',
            name='pending_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tg_bind_pending', to=settings.AUTH_USER_MODEL, verbose_name="Admin tasdig'ini kutayotgan foydalanuvchi"),
        ),
    ]
