# Generated by Django 6.0.7 on 2026-08-03 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0030_telegrambindstate_pending_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(blank=True, choices=[('', "— (lavozim yo'q)"), ('director', 'Direktor'), ('pto', 'PTO'), ('prorab', 'Prorab'), ('snab', 'Snabjeniye')], max_length=16, verbose_name='Lavozim'),
        ),
    ]
