# Generated by Django 6.0.7 on 2026-08-03 12:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0031_alter_userprofile_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='limitchangerequest',
            name='snab_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name="Snabjeniye ko'rgan sana"),
        ),
        migrations.AddField(
            model_name='limitchangerequest',
            name='snab_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='limit_requests_snab', to=settings.AUTH_USER_MODEL, verbose_name="Snabjeniye ko'rdi"),
        ),
        migrations.AlterField(
            model_name='limitchangerequest',
            name='status',
            field=models.CharField(choices=[('snab', "Snabjeniye ko'rigida"), ('pto2', 'PTO xulosasida'), ('dir', "Direktor tasdig'ida"), ('adm', "Admin tasdig'ida"), ('pending', 'Kutilmoqda'), ('approved', 'Tasdiqlangan'), ('rejected', 'Rad etilgan')], default='dir', max_length=16, verbose_name='Holati'),
        ),
    ]
