# Generated by Django 6.0.7 on 2026-08-04 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0032_limitchangerequest_snab_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialrequestitem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Kiritilgan sana'),
        ),
        migrations.AddField(
            model_name='materialrequestitem',
            name='kind',
            field=models.CharField(choices=[('material', 'Material'), ('labor', 'Ish haqi'), ('machinery', 'Mashina chasti'), ('other', "Ko'zda tutilmagan xarajatlar")], default='material', max_length=16, verbose_name='Turi'),
        ),
        migrations.AddField(
            model_name='materialrequestitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='Narxi (1 birlik, ixtiyoriy)'),
        ),
    ]
