# Generated by Django 6.0.7 on 2026-08-04 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0033_materialrequestitem_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='materialrequest',
            options={'ordering': ['-created_at'], 'verbose_name': "Prorab so'rovi", 'verbose_name_plural': "Prorab so'rovlari"},
        ),
    ]
