# Generated by Django 6.0.7 on 2026-08-08 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0034_alter_materialrequest_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='limitchangeitem',
            name='bolim',
            field=models.CharField(blank=True, max_length=200, verbose_name="Bo'lim"),
        ),
        migrations.AddField(
            model_name='limitchangeitem',
            name='masul',
            field=models.CharField(blank=True, max_length=120, verbose_name="Mas'ul shaxs"),
        ),
        migrations.AddField(
            model_name='limititem',
            name='bolim',
            field=models.CharField(blank=True, max_length=200, verbose_name="Bo'lim"),
        ),
        migrations.AddField(
            model_name='limititem',
            name='masul',
            field=models.CharField(blank=True, max_length=120, verbose_name="Mas'ul shaxs"),
        ),
    ]
