# Generated by Django 6.0.7 on 2026-08-10 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0035_limitchangeitem_bolim_limitchangeitem_masul_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='grafik_end',
            field=models.DateField(blank=True, null=True, verbose_name='Grafik tugash sanasi'),
        ),
    ]
