# Generated by Django 6.0.7 on 2026-08-11 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0036_project_grafik_end'),
    ]

    operations = [
        migrations.AddField(
            model_name='grafikrow',
            name='muddat',
            field=models.PositiveIntegerField(default=0, verbose_name='Muddat (kun)'),
        ),
        migrations.AddField(
            model_name='grafikrow',
            name='muddat_boshi',
            field=models.DateField(blank=True, null=True, verbose_name='Ish boshlanishi'),
        ),
    ]
