# Generated by Django 6.0.7 on 2026-08-11 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0037_grafikrow_muddat_grafikrow_muddat_boshi'),
    ]

    operations = [
        migrations.AddField(
            model_name='grafikrow',
            name='srok_off',
            field=models.JSONField(blank=True, default=list, verbose_name='Srokdan chiqarilgan kunlar'),
        ),
    ]
