# Generated by Django 6.0.7 on 2026-08-12 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0038_grafikrow_srok_off'),
    ]

    operations = [
        migrations.AddField(
            model_name='grafikrow',
            name='srok_on',
            field=models.JSONField(blank=True, default=list, verbose_name="Qo'shimcha srok kunlari"),
        ),
    ]
