# Generated by Django 6.0.7 on 2026-08-13 12:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0039_grafikrow_srok_on'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='limitchangerequest',
            name='edited_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Oxirgi tahrir sanasi'),
        ),
        migrations.AddField(
            model_name='limitchangerequest',
            name='edited_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='limit_requests_edited', to=settings.AUTH_USER_MODEL, verbose_name='Oxirgi tahrir'),
        ),
        migrations.AddField(
            model_name='limitchangerequest',
            name='pto2_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='PTO xulosasi sanasi'),
        ),
        migrations.AddField(
            model_name='limitchangerequest',
            name='pto2_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='limit_requests_pto2', to=settings.AUTH_USER_MODEL, verbose_name='PTO xulosasini yubordi'),
        ),
        migrations.AddField(
            model_name='weeklyrequest',
            name='edited_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Oxirgi tahrir sanasi'),
        ),
        migrations.AddField(
            model_name='weeklyrequest',
            name='edited_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='weekly_edited', to=settings.AUTH_USER_MODEL, verbose_name='Oxirgi tahrir'),
        ),
    ]
