# Generated by Django 6.0.7 on 2026-08-14 13:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0040_limitchangerequest_edited_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='grafikrow',
            name='note_tarix',
            field=models.JSONField(blank=True, default=list, verbose_name='Izoh tarixi'),
        ),
        migrations.CreateModel(
            name='GrafikTasdiq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('dir', "Direktor tasdig'ida"), ('adm', "Admin tasdig'ida"), ('approved', 'Tasdiqlangan'), ('rejected', 'Rad etilgan')], default='dir', max_length=16, verbose_name='Holati')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yuborilgan sana')),
                ('director_at', models.DateTimeField(blank=True, null=True, verbose_name="Direktor tasdig'i sanasi")),
                ('decided_at', models.DateTimeField(blank=True, null=True, verbose_name='Admin qarori sanasi')),
                ('decision_note', models.CharField(blank=True, max_length=500, verbose_name='Rad etish sababi')),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grafik_tasdiq_adm', to=settings.AUTH_USER_MODEL, verbose_name='Admin tasdiqladi')),
                ('director_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grafik_tasdiq_dir', to=settings.AUTH_USER_MODEL, verbose_name='Direktor tasdiqladi')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grafik_tasdiqlar', to='projects.project', verbose_name='Obyekt')),
                ('yubordi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grafik_tasdiq_yuborgan', to=settings.AUTH_USER_MODEL, verbose_name='Yubordi (PTO)')),
            ],
            options={
                'verbose_name': "Grafik tasdig'i",
                'verbose_name_plural': 'Grafik tasdiqlari',
                'ordering': ['-created_at'],
            },
        ),
    ]
