# Generated by Django 6.0.7 on 2026-08-15 07:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0041_grafikrow_note_tarix_grafiktasdiq'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Xabar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matn', models.TextField(max_length=2000, verbose_name='Xabar matni')),
                ('muhimlik', models.CharField(choices=[('oddiy', 'Oddiy'), ('muhim', 'Muhim'), ('shoshilinch', 'Shoshilinch')], default='oddiy', max_length=12, verbose_name='Muhimlik')),
                ('hammaga', models.BooleanField(default=False, verbose_name='Hammaga')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yuborilgan sana')),
                ('kimga', models.ManyToManyField(blank=True, related_name='xabarlar_olgan', to=settings.AUTH_USER_MODEL, verbose_name='Kimga')),
                ('yubordi', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='xabarlar_yuborgan', to=settings.AUTH_USER_MODEL, verbose_name='Yubordi (admin)')),
            ],
            options={
                'verbose_name': 'Xabar',
                'verbose_name_plural': 'Xabarlar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='XabarOqildi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oqilgan_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='xabar_oqilgan', to=settings.AUTH_USER_MODEL)),
                ('xabar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oqilganlar', to='projects.xabar')),
            ],
            options={
                'verbose_name': "Xabar o'qildi",
                'verbose_name_plural': "Xabar o'qilganlar",
                'constraints': [models.UniqueConstraint(fields=('xabar', 'user'), name='uniq_xabar_user_oqildi')],
            },
        ),
    ]
