# Generated by Django 6.0.7 on 2026-08-18 11:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0043_alter_userprofile_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Moliya',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summa', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='Berilgan summa')),
                ('miqdor', models.DecimalField(blank=True, decimal_places=3, max_digits=18, null=True, verbose_name='Berilgan miqdor')),
                ('izoh', models.CharField(blank=True, max_length=300, verbose_name='Izoh (kassa/karta/avans...)')),
                ('sana', models.DateField(verbose_name="To'lov sanasi")),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yozilgan vaqt')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moliyalar', to='projects.weeklyrequestitem', verbose_name='Haftalik qatori')),
                ('yozdi', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moliya_yozgan', to=settings.AUTH_USER_MODEL, verbose_name='Yozdi (buxgalter)')),
            ],
            options={
                'verbose_name': "Moliyalashtirish (to'lov)",
                'verbose_name_plural': "Moliyalashtirish (to'lovlar)",
                'ordering': ['-sana', '-id'],
            },
        ),
    ]
