# Generated by Django 6.0.7 on 2026-08-19 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0044_moliya'),
    ]

    operations = [
        migrations.AddField(
            model_name='weeklyrequestitem',
            name='bolim',
            field=models.CharField(blank=True, max_length=200, verbose_name="Bo'lim"),
        ),
    ]
