# Generated by Django 6.0.7 on 2026-09-15 12:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0045_weeklyrequestitem_bolim'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LimitNavbat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('izoh', models.CharField(blank=True, max_length=300, verbose_name='Izoh')),
                ('items', models.JSONField(default=list)),
                ('idx', models.IntegerField(default=0, verbose_name='Joriy bosqich')),
                ('status', models.CharField(default='active', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='limit_navbatlar', to='projects.project')),
                ('xabar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='projects.xabar')),
            ],
            options={
                'verbose_name': 'Limit navbati (ketma-ket)',
                'verbose_name_plural': 'Limit navbatlari',
            },
        ),
    ]
