# Generated by Django 6.0.6 on 2026-10-01 04:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0049_limit_sana'),
    ]

    operations = [
        migrations.AddField(
            model_name='limitchangeitem',
            name='asl',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='takliflar', to='projects.limititem', verbose_name='Asl qator'),
        ),
    ]
