# Generated by Django 6.0.6 on 2026-10-01 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0050_limitchangeitem_asl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='limitchangerequest',
            name='status',
            field=models.CharField(choices=[('draft', 'Qoralama'), ('snab', "Snabjeniye ko'rigida"), ('pto2', 'PTO xulosasida'), ('dir', "Direktor tasdig'ida"), ('adm', "Admin tasdig'ida"), ('pending', 'Kutilmoqda'), ('approved', 'Tasdiqlangan'), ('rejected', 'Rad etilgan')], default='dir', max_length=16, verbose_name='Holati'),
        ),
    ]
