# Generated by Django 6.0.6 on 2026-10-01 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0051_limitchangerequest_draft'),
    ]

    operations = [
        migrations.AddField(
            model_name='limitchangeitem',
            name='boshlangich_qty',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=18, verbose_name='Limitgacha bajarilgan (miqdor)'),
        ),
        migrations.AddField(
            model_name='limitchangeitem',
            name='boshlangich_sum',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='Limitgacha bajarilgan (summa)'),
        ),
        migrations.AddField(
            model_name='limititem',
            name='boshlangich_qty',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=18, verbose_name='Limitgacha bajarilgan (miqdor)'),
        ),
        migrations.AddField(
            model_name='limititem',
            name='boshlangich_sum',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='Limitgacha bajarilgan (summa)'),
        ),
    ]
