# Generated by Django 6.0.6 on 2026-10-02 04:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0052_boshlangich_fakt'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='limitchangerequest',
            name='prov_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Proverchik tekshiruvi sanasi'),
        ),
        migrations.AddField(
            model_name='limitchangerequest',
            name='prov_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='limit_requests_prov', to=settings.AUTH_USER_MODEL, verbose_name='Proverchik tekshirdi'),
        ),
        migrations.AlterField(
            model_name='limitchangerequest',
            name='status',
            field=models.CharField(choices=[('draft', 'Qoralama'), ('snab', "Snabjeniye ko'rigida"), ('pto2', 'PTO xulosasida'), ('dir', "Direktor tasdig'ida"), ('prov', 'Proverchik tekshiruvida'), ('adm', "Admin tasdig'ida"), ('pending', 'Kutilmoqda'), ('approved', 'Tasdiqlangan'), ('rejected', 'Rad etilgan')], default='dir', max_length=16, verbose_name='Holati'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(blank=True, choices=[('', "— (lavozim yo'q)"), ('director', 'Direktor'), ('pto', 'PTO'), ('prorab', 'Prorab'), ('snab', 'Snabjeniye'), ('bux', 'Buxgalter'), ('prov', 'Proverchik (tekshiruvchi)')], max_length=16, verbose_name='Lavozim'),
        ),
    ]
