# Generated by Django 6.0.6 on 2026-10-02 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0053_proverchik'),
    ]

    operations = [
        migrations.AddField(
            model_name='weeklyrequest',
            name='tahrir_ruxsat',
            field=models.BooleanField(default=False, verbose_name='Tahrirga admin ruxsati'),
        ),
    ]
