# Generated by Django 6.0.6 on 2026-06-25 07:50

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=64, unique=True, verbose_name='Kod / artikul')),
                ('name', models.CharField(max_length=255, verbose_name='Nomi')),
                ('unit', models.CharField(help_text='dona, kg, m3, m2, t ...', max_length=32, verbose_name="O'lchov birligi")),
            ],
            options={
                'verbose_name': 'Material',
                'verbose_name_plural': 'Materiallar',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MaterialCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Kategoriya')),
            ],
            options={
                'verbose_name': 'Material kategoriyasi',
                'verbose_name_plural': 'Material kategoriyalari',
            },
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_number', models.CharField(blank=True, max_length=64, verbose_name='Hujjat / nakladnoy raqami')),
                ('date', models.DateField(verbose_name='Sana')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='Izoh')),
                ('is_posted', models.BooleanField(default=False, editable=False, verbose_name='Qayd qilingan')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Prixod (kirim)',
                'verbose_name_plural': 'Prixodlar (kirim)',
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nomi')),
                ('inn', models.CharField(blank=True, max_length=20, verbose_name='STIR')),
                ('phone', models.CharField(blank=True, max_length=32, verbose_name='Telefon')),
            ],
            options={
                'verbose_name': 'Yetkazib beruvchi',
                'verbose_name_plural': 'Yetkazib beruvchilar',
            },
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient', models.CharField(blank=True, max_length=255, verbose_name="Kim oldi (brigada / mas'ul)")),
                ('doc_number', models.CharField(blank=True, max_length=64, verbose_name='Hujjat raqami')),
                ('date', models.DateField(verbose_name='Sana')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='Izoh')),
                ('is_posted', models.BooleanField(default=False, editable=False, verbose_name='Qayd qilingan')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('work_section', models.ForeignKey(blank=True, help_text='Qaysi ishga sarflandi', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='issues', to='projects.worksection', verbose_name="Ish bo'limi")),
            ],
            options={
                'verbose_name': 'Rasxod (chiqim)',
                'verbose_name_plural': 'Rasxodlar (chiqim)',
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='IssueItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))], verbose_name='Miqdor')),
                ('unit_cost', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=18, verbose_name='Hisobiy narx (1 birlik)')),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='ombor.issue')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ombor.material', verbose_name='Material')),
            ],
            options={
                'verbose_name': 'Rasxod qatori',
                'verbose_name_plural': 'Rasxod qatorlari',
            },
        ),
        migrations.AddField(
            model_name='material',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ombor.materialcategory', verbose_name='Kategoriya'),
        ),
        migrations.CreateModel(
            name='ReceiptItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))], verbose_name='Miqdor')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=18, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Kirim narxi (1 birlik)')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ombor.material', verbose_name='Material')),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='ombor.receipt')),
            ],
            options={
                'verbose_name': 'Prixod qatori',
                'verbose_name_plural': 'Prixod qatorlari',
            },
        ),
        migrations.AddField(
            model_name='receipt',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='receipts', to='ombor.supplier', verbose_name='Yetkazib beruvchi'),
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nomi')),
                ('project', models.ForeignKey(blank=True, help_text="Bo'sh = markaziy ombor", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='warehouses', to='projects.project', verbose_name='Obyekt')),
            ],
            options={
                'verbose_name': 'Ombor',
                'verbose_name_plural': 'Omborlar',
            },
        ),
        migrations.AddField(
            model_name='receipt',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receipts', to='ombor.warehouse', verbose_name='Ombor'),
        ),
        migrations.AddField(
            model_name='issue',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='issues', to='ombor.warehouse', verbose_name='Ombor'),
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('in', 'Kirim'), ('out', 'Chiqim')], max_length=3)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=18, verbose_name='Miqdor (ishorali)')),
                ('unit_cost', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='Birlik narxi')),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='Summa (ishorali)')),
                ('date', models.DateField()),
                ('doc_type', models.CharField(max_length=16)),
                ('doc_id', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='ombor.material')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='projects.project')),
                ('work_section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='projects.worksection')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='ombor.warehouse')),
            ],
            options={
                'verbose_name': 'Harakat',
                'verbose_name_plural': 'Harakatlar jurnali',
                'ordering': ['date', 'id'],
                'indexes': [models.Index(fields=['warehouse', 'material', 'date'], name='ombor_stock_warehou_a7b68c_idx'), models.Index(fields=['doc_type', 'doc_id'], name='ombor_stock_doc_typ_1f5b51_idx')],
            },
        ),
        migrations.CreateModel(
            name='StockBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, default=0, max_digits=18, verbose_name='Qoldiq miqdori')),
                ('total_value', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='Qoldiq qiymati')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balances', to='ombor.material')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balances', to='ombor.warehouse')),
            ],
            options={
                'verbose_name': 'Ostatka',
                'verbose_name_plural': 'Ostatkalar',
                'constraints': [models.UniqueConstraint(fields=('warehouse', 'material'), name='uniq_balance_wh_material')],
            },
        ),
    ]
