# Generated by Django 6.0.6 on 2026-07-08 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ombor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='prixod/%Y/%m/', verbose_name='Mahsulot rasmi'),
        ),
    ]
