# Generated by Django 6.0.6 on 2026-07-08 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ombor', '0002_receipt_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouse',
            name='code',
            field=models.CharField(blank=True, max_length=64, verbose_name='Kod'),
        ),
    ]
