# Generated by Django 6.0.7 on 2026-08-05 05:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ombor', '0003_warehouse_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReceiptImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turi', models.CharField(choices=[('product', 'Mahsulot rasmi'), ('nakladnoy', 'Nakladnoy rasmi')], default='product', max_length=16, verbose_name='Turi')),
                ('image', models.ImageField(upload_to='prixod/%Y/%m/', verbose_name='Rasm')),
                ('summa', models.DecimalField(blank=True, decimal_places=2, help_text='Faqat nakladnoy rasmi uchun', max_digits=18, null=True, verbose_name='Nakladnoy itogo summasi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='ombor.receipt', verbose_name='Prixod')),
            ],
            options={
                'verbose_name': 'Prixod rasmi',
                'verbose_name_plural': 'Prixod rasmlari',
            },
        ),
    ]
