# Generated by Django 6.0.7 on 2026-08-05 09:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ombor', '0004_receiptimage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='prorab_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name="Prorab tasdig'i vaqti"),
        ),
        migrations.AddField(
            model_name='issue',
            name='prorab_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rasxod_tasdiqlagan', to=settings.AUTH_USER_MODEL, verbose_name='Miqdorni tasdiqlagan prorab'),
        ),
        migrations.AddField(
            model_name='issue',
            name='source_receipt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auto_issues', to='ombor.receipt', verbose_name='Manba prixod (avto)'),
        ),
        migrations.AddField(
            model_name='receipt',
            name='obyektga_avto',
            field=models.BooleanField(default=False, verbose_name="Obyektga to'g'ridan-to'g'ri (rasxodga avto o'tadi)"),
        ),
    ]
