# Generated by Django 6.0.7 on 2026-08-06 05:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ombor', '0005_issue_prorab_at_issue_prorab_by_issue_source_receipt_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='rad_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Rad vaqti'),
        ),
        migrations.AddField(
            model_name='receipt',
            name='rad_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prixod_rad_etgan', to=settings.AUTH_USER_MODEL, verbose_name='Rad etgan prorab'),
        ),
        migrations.AddField(
            model_name='receipt',
            name='rad_note',
            field=models.CharField(blank=True, max_length=500, verbose_name='Prorab rad sababi'),
        ),
    ]
